//
//  LoginRouter.swift
//  Dezeer
//
//  Created by Levin Ivan on 11.07.2020.
//  Copyright (c) 2020 Levin Ivan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
//    func routeToSomewhere()
}

protocol LoginDataPassing: class {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
}

// MARK: - LoginRoutingLogic
extension LoginRouter: LoginRoutingLogic {
    
//    func routeToSomewhere() {
//        let vc = Builder.build()
//        viewController?.show(vc, sender: nil)
//    }
    
}
