//
//  LoginWorker.swift
//  Dezeer
//
//  Created by Levin Ivan on 11.07.2020.
//  Copyright (c) 2020 Levin Ivan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker {

    func fetchData(completion: @escaping (Result<String, AppError>) -> Void) {
        let text: String? = "Success"
        if let text = text {
            completion(.success(text))
        } else {
            completion(.failure(AppError(message: "Failure")))
        }
    }

}
