//
//  LoginPresenter.swift
//  Dezeer
//
//  Created by Levin Ivan on 11.07.2020.
//  Copyright (c) 2020 Levin Ivan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic: HUDPresentationLogic, ErrorMessagePresentationLogic {
    func presentFetchingResult(response: Login.Fetching.Response)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    var hudViewController: HUDDisplayLogic? { return viewController }
    var errorViewController: ErrorMessageDisplayLogic? { return viewController }
    
    // MARK: - LoginPresentationLogic
    
    func presentFetchingResult(response: Login.Fetching.Response) {
        let viewModel = Login.Fetching.ViewModel()
        viewController?.displayFetchingResult(viewModel: viewModel)
    }
    
    // MARK: - Private methods
}
