//
//  LoginView.swift
//  Dezeer
//
//  Created by Levin Ivan on 11.07.2020.
//  Copyright (c) 2020 Levin Ivan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TinyConstraints

class LoginView: UIView {
    
    init() {
        super.init(frame: .zero)
        setup()
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    private func setup() {
        backgroundColor = UIColor.utkBackground
        initialLayout()
    }
    
    private func initialLayout() {
        
    }
}
