//
//  LoginBuilder.swift
//  Dezeer
//
//  Created by Levin Ivan on 11.07.2020.
//  Copyright (c) 2020 Levin Ivan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginBuilder {
    
    static func build() -> LoginViewController {
        let viewController = configureModule()
        viewController.title = "Login"
        return viewController
    }
    
    private static func configureModule() -> LoginViewController {
        let viewController = LoginViewController()
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        return viewController
    }
    
}
